#!/usr/bin/env bash
# This script displays the time for 12hrs and 59min

hour=0
minute=1

while [ $hour -le 12 ]
do
echo "Hour: $hour"
while [ $minute -le 59 ]
do
echo "$minute"
((minute++))
done
((hour++))
done
